data = [
    {"list": "Juazeiro do Norte"},
    {"list": "Camaçari"},
    {"list": "Bayeux"},
    {"list": "Valparaíso de Goiás"},
    {"list": "Jundiaí"},
    {"list": "Recife"},
    {"list": "Diadema"},
    {"list": "Olinda"},
    {"list": "Olinda"},
    {"list": "Itajaí"},
    {"list": "Belford Roxo"},
    {"list": "Jundiaí"},
    {"list": "Curitiba"},
    {"list": "Juiz de Fora"},
    {"list": "Cametá"},
    {"list": "Cajazeiras"},
    {"list": "Anápolis"},
    {"list": "Mauá"},
    {"list": "João Pessoa"},
    {"list": "Uberlândia"},
    {"list": "Marabá"},
    {"list": "Divinópolis"},
    {"list": "Ribeirão das Neves"},
    {"list": "Mogi das Cruzes"},
    {"list": "São José"},
    {"list": "Codó"},
    {"list": "Belém"},
    {"list": "Fortaleza"},
    {"list": "Sobral"},
    {"list": "Caruaru"},
    {"list": "Itapipoca"},
    {"list": "Fortaleza"},
    {"list": "Novo Hamburgo"},
    {"list": "Juazeiro do Norte"},
    {"list": "São Gonçalo"},
    {"list": "Ponta Grossa"},
    {"list": "Balsas"},
    {"list": "Mauá"},
    {"list": "Rio Verde"},
    {"list": "Criciúma"},
    {"list": "Olinda"},
    {"list": "Duque de Caxias"},
    {"list": "Niterói"},
    {"list": "Itapipoca"},
    {"list": "Londrina"},
    {"list": "Sousa"},
    {"list": "São José"},
    {"list": "Patos"},
    {"list": "Anápolis"},
    {"list": "São José dos Pinhais"},
    {"list": "São Gonçalo"},
    {"list": "Campos dos Goytacazes"},
    {"list": "Fortaleza"},
    {"list": "Jaboatão dos Guararapes"},
    {"list": "Gravataí"},
    {"list": "Valparaíso de Goiás"},
    {"list": "Juazeiro do Norte"},
    {"list": "Vitória da Conquista"},
    {"list": "Ananindeua"},
    {"list": "Rio Grande"},
    {"list": "Itabuna"},
    {"list": "Blumenau"},
    {"list": "Joinville"},
    {"list": "Santa Maria"},
    {"list": "Chapecó"},
    {"list": "Blumenau"},
    {"list": "Patos"},
    {"list": "Gravataí"},
    {"list": "Novo Hamburgo"},
    {"list": "Barra do Corda"},
    {"list": "Rio Grande"},
    {"list": "Sete Lagoas"},
    {"list": "Bragança"},
    {"list": "Parauapebas"},
    {"list": "Vitória da Conquista"},
    {"list": "Mauá"},
    {"list": "Timon"},
    {"list": "Abaetetuba"},
    {"list": "Paranaguá"},
    {"list": "Foz do Iguaçu"},
    {"list": "Santa Inês"},
    {"list": "Cabo de Santo Agostinho"},
    {"list": "Campina Grande"},
    {"list": "Ribeirão Preto"},
    {"list": "Juazeiro do Norte"},
    {"list": "Rio Verde"},
    {"list": "Abaetetuba"},
    {"list": "Maranguape"},
    {"list": "Juazeiro do Norte"},
    {"list": "Açailândia"},
    {"list": "Abaetetuba"},
    {"list": "Caruaru"},
    {"list": "Contagem"},
    {"list": "Rio Verde"},
    {"list": "Águas Lindas de Goiás"},
    {"list": "Fortaleza"},
    {"list": "Castanhal"},
    {"list": "São João de Meriti"},
    {"list": "Piracicaba"},
    {"list": "Guarapuava"}
]